name: Pipeline CI

on:
  push:
    branches: [ "dev", "prod" ]
  pull_request:
    branches: [ "dev", "prod" ]

jobs:
  backend-tests:
    name: Tests Backend (Node/Jest)
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4
    - name: Configurer Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: ./backend/package-lock.json
    - name: Installation des paquets
      run: npm install
    - name: Lancer Jest
      run: npm run test:coverage